name: Hydra AI Swarm
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Bu butonla botu elle başlatmanı sağlar

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # En güncel sürümü GitHub bize sağlıyor!

      - name: Install Dependencies
        - name: Install Dependencies
        run: npm install mineflayer@4.20.0 mineflayer-pathfinder@2.4.3 minecraft-data vec3 @supabase/supabase-js groq-sdk

      - name: Run Hydra Bot
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: node index.js
